version: "3.7"
services:
  api:
    ports:
      - "3333:3333"
    image: "obyz/tayssir-covid-api:latest"
  front:
    ports:
      - "80:80"
    image: "obyz/tayssir-covid-front:latest"
  admin:
    ports:
      - "8081:8081"
    image: "obyz/tayssir-covid-admin:latest"
