name: Docker Image CI

on:
  push:
    branches: [ init-dockerfile ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: login into DockerHub
      run: docker login -u ${{secrets.dockerlogin}} -p ${{secrets.dockertoken}}

    - name: install project
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install # will run `yarn install` command

      # Building API
    - name: Building api
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build:api


    - name: Build api Docker image
      run: docker build . --file dockerfiles/Dockerfile-api --tag obyz/tayssir-covid-api:latest

      # Building Front
    - name: push api Docker image
      if: success()
      run: docker push obyz/tayssir-covid-api:latest

    - name: Building front
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build

      # Pushing images to repo
    - name: Build api Docker image
      run: docker build . --file dockerfiles/Dockerfile-front --tag obyz/tayssir-covid-front:latest

    - name: push front Docker image
      if: success()
      run: docker push obyz/tayssir-covid-front:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: run App Remotly
        uses: appleboy/ssh-action@master
        with:
          host: 51.15.82.73
          username: root
          key: ${{secrets.key}}
          passphrase: ${{secrets.passphrase}}
          port: 22
          script: |
            docker image ls
            docker ps

