name: Docker Image CI

on:
  push:
    branches: [ init-dockerfile ]
  pull_request:
    branches: [ master ]

jobs:

#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag obyz/tayssir-covid:latest
#    - name: login into DockerHub
#      if: success()
#      run: docker login -u ${{secrets.dockerlogin}} -p ${{secrets.dockertoken}}
#    - name: push the Docker image
#      if: success()
#      run: docker push obyz/tayssir-covid:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: run App Remotly
        uses: appleboy/ssh-action@master
        with:
          host: 51.15.82.73
          username: root
          key: ${{secrets.key}}
          passphrase: ${{secrets.passphrase}}
          port: 22
          script: whoami

